### PR TITLE
update 11-j9 to jdk-11.0.2+9_openj9-0.12.1

### PR DESCRIPTION
**Pull request by gdams**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

closes: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/75

### CODE REVIEW

**Comment by karianna** [comment]
@gdams needs a rebase

**Comment by VonUniGE** [comment]
- The URL specified in the cask which is
```
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9/OpenJDK11U-jdk_x64_mac_openj9-0.12.1_jdk-11.0.2_9_openj9-0.12.1_11.0.2_9.tar.gz
```
gives 404.
 - The URL of the available tar.gz file is
```
https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.2%2B9_openj9-0.12.1/OpenJDK11U-jdk_x64_mac_openj9_11.0.2_9_openj9-0.12.1_openj9-0.12.1.tar.gz
```
gives the tar.gz file but seems wrong because of the three time repetition of `openj9` in the filename.

**Comment by gdams** [comment]
@VonUniGE we changed the naming for this release. Can you update the URL and we can then merge this?

**Comment by VonUniGE** [comment]
The URL is now correct but it seems that there is other changes in the tar.gz file.

**Pull request merged**
