### PR TITLE
WIP: Create adoptopenjdk8-jre.rb

### PR DESCRIPTION
**Pull request by gdams**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask in a similar way to the existing casks.
- [x] Added new cask to the README.md
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.

### CODE REVIEW

**Comment by karianna** [comment]
@gdams Is this still WIP? It LGTM

**Comment by gdams** [comment]
@karianna travis failed so I'll have to test more

**Comment by VonUniGE** [comment]
I've made a new branch for which I can pass all items on the checklist:
https://github.com/VonUniGE/homebrew-openjdk/tree/adoptopenjdk8-jre

**Comment by gdams** [comment]
@VonUniGE want to create a PR and close mine?

**Comment by VonUniGE** [comment]
If it's OK for you, I think it should be easier.

**Pull request merged**
