### PR TITLE
add desc stanza to casks

### PR DESCRIPTION
**Pull request by gdams**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Review by karianna — APPROVED** [review]
lgtm

**Comment by karianna** [comment]
@gdams some unhappy checks it seems

**Comment by karianna** [comment]
@gdams - Does this need to still pass more PR tester runs?  Look like it stalled.

**Comment by gdams** [comment]
Yeah it's slowly getting there, it's got to run a full test for every cask

**Pull request merged**
