### PR TITLE
Add Cask for OpenJ9 on latest OpenJDK (11.0.1_13)

### PR DESCRIPTION
**Pull request by habibalamin**
This should partially resolve both #38 and #41.

### CODE REVIEW

**Comment by karianna** [comment]
Gated by us actually getting an 11.0.1 release out.

**Comment by gdams** [comment]
@habibalamin please rebase this on master

**Comment by habibalamin** [comment]
Sorry for the late response. I discovered that the software I was using was dependent on a JDK 8, so this was no longer useful to me. However, I've made the requested changes and am leaving it with you guys now.

FYI, the reason I named it without a version suffix is that it's conventional to have no suffix for the latest version, which is how the formula in the default tap is. I've renamed it to match the convention of this tap (which I didn't spot at first), but I really think the other v11 variant should also lose the suffix (or add a symbolic link for each latest version).

Anyway, that's just my opinion, but it's only a minor gripe. Thanks for providing this tap.

**Comment by karianna** [comment]
@gdams - Does this still have value - should we patch the PR and land it?

**Comment by gdams** [comment]
does the release actually exist?

**Comment by karianna** [comment]
Yes _ think @sxa555 released this some time ago.

**Comment by gdams** [comment]
so there are currently some linter failures and also the URL doesn't seem to work so we need to check this...

**Comment by VonUniGE** [comment]
Here is a working version of the cask with a corrected URL and no offense with:

    brew cask style --fix

https://github.com/VonUniGE/homebrew-openjdk/tree/adoptopenjdk11-openj9

The question now is about the installation path should we keep:

`/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.1.jdk`

or should we use:

`/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.1-openj9.jdk`

Personally, I'm for the second solution which allows to run Hotspot and OpenJ9 in parallel but I'm waiting for a feedback before modifying the cask.

**Comment by turesheim** [comment]
> `/Library/Java/JavaVirtualMachines/adoptopenjdk-11.0.1-openj9.jdk`

+1 to this solution. It would be very useful to be able to run both VM's.

**Comment by VonUniGE** [comment]
Ok, I can now install adoptopenjdk11.rb and adoptopenjdk11-openj9.rb and switch between both with JAVA_HOME.

https://github.com/VonUniGE/homebrew-openjdk/blob/adoptopenjdk11-openj9/Casks/adoptopenjdk11-openj9.rb

**Comment by gdams** [comment]
closing in favour of @VonUniGE's fork at https://github.com/AdoptOpenJDK/homebrew-openjdk/pull/53

**Pull request closed without merging**
